-- Automatisch gegenereerd vanuit data/menu-export.json (scripts/generate-menu-seed.mjs)

-- Categorieën
insert into categories (name, sort_order) values ('GEBAK', 0);
insert into categories (name, sort_order) values ('EIEREN', 1);
insert into categories (name, sort_order) values ('ONTBIJT', 2);
insert into categories (name, sort_order) values ('TOSTI''S', 3);
insert into categories (name, sort_order) values ('MSEMEN / PANNENKOEK', 4);
insert into categories (name, sort_order) values ('PANINI''S', 5);
insert into categories (name, sort_order) values ('BELEGDE BROODJES', 6);
insert into categories (name, sort_order) values ('HARTIGE HAPJES', 7);
insert into categories (name, sort_order) values ('WARME BROODJES', 8);
insert into categories (name, sort_order) values ('SOEP', 9);
insert into categories (name, sort_order) values ('SALADES', 10);
insert into categories (name, sort_order) values ('SMOOTHIES', 11);
insert into categories (name, sort_order) values ('MILKSHAKES', 12);
insert into categories (name, sort_order) values ('WARME DRANKJES', 13);
insert into categories (name, sort_order) values ('FRISDRANK', 14);

-- Gerechten
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'GEBAK'), 'Pistache Cheesecake', null, 5.95, ARRAY['Ei', 'Gluten', 'Melk', 'Noten', 'Pinda''s', 'Halal'], false, 0);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'GEBAK'), 'Framboos White Choco Cheesecake', null, 5.95, ARRAY['Ei', 'Gluten', 'Melk', 'Noten', 'Pinda''s', 'Halal'], false, 1);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'GEBAK'), 'Nutella Cookie', null, 2.95, ARRAY['Ei', 'Gluten', 'Melk', 'Noten', 'Sesam', 'Halal'], false, 2);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'EIEREN'), '2 EITJES', '2 eitjes geserveerd met brood', 5.50, ARRAY['Ei'], true, 3);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'EIEREN'), '2 EITJES SPECIAAL', 'chatarworst, geraspte kaas, La’vache qui rit en olijven', 7.95, ARRAY['Ei', 'Melk', 'Halal'], true, 4);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'EIEREN'), 'ROEREI', '3 roereitjes worden geserveerd met stokbrood.', 5.95, ARRAY['Ei'], true, 5);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'EIEREN'), 'ROEREI SPECIAAL', 'chatarworst, geraspte kaas, La’vache qui rit en olijven.', 8.50, ARRAY['Ei', 'Melk', 'Halal'], true, 6);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'EIEREN'), 'OMELET', 'omelet met 3 eieren', 6.95, ARRAY['Ei'], true, 7);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'EIEREN'), 'OMELET KAAS', 'Beemster geraspte kaas.', 7.95, ARRAY['Ei', 'Melk'], true, 8);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'EIEREN'), 'OMELET SPECIAAL', 'chatarworst, geraspte kaas, La’vache qui rit en olijven', 8.95, ARRAY['Ei', 'Melk', 'Halal'], true, 9);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'EIEREN'), 'OMELET ZALM', 'Omelet met zalmsnippers en kaas.', 11.95, ARRAY['Ei', 'Melk', 'Vis'], true, 10);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'EIEREN'), 'OMELET TONIJN', 'Omelet met tonijn en cheddar kaas.', 10.95, ARRAY['Ei', 'Melk', 'Vis'], true, 11);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'EIEREN'), 'ROER EI MET SUCUCK', null, 8.95, '{}', true, 12);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'EIEREN'), 'Extra brood', null, 1.00, '{}', true, 13);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'ONTBIJT'), 'BELDI ONTBIJTJE', 'Twee eitjes speciaal, met chatar worst geraspte kaas en olijven en la vach qu ri kleine jus ''d orange en koffie of thee naar keuze.', 12.95, ARRAY['Mild', 'Ei', 'Melk', 'Halal'], true, 14);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'ONTBIJT'), 'MAROKKAANTJE', 'Msemen, baghrir, harcha, la vache qui rit, honing. Kleine Jus d''orange en koffie of thee.', 14.95, ARRAY['Gluten'], true, 15);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'TOSTI''S'), 'KAAS', null, 3.95, ARRAY['Gluten'], true, 16);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'TOSTI''S'), 'HAM - KAAS', null, 4.95, ARRAY['Gluten', 'Halal'], true, 17);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'TOSTI''S'), 'TONIJN - KAAS', null, 5.95, ARRAY['Gluten', 'Vis'], true, 18);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'TOSTI''S'), 'GRILLWORST - KAAS', null, 5.50, ARRAY['Gluten', 'Halal'], true, 19);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'TOSTI''S'), 'TOSTI KAAS-SUCUK', 'Tosti kaas met sucuk', 5.50, ARRAY['Gluten', 'Halal'], true, 20);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'MSEMEN / PANNENKOEK'), 'MSEMEN', 'Traditionele Marokkaanse pannenkoek.', 3.95, ARRAY['Gluten', 'Vegetarisch'], true, 21);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'MSEMEN / PANNENKOEK'), 'MSEMEN KAAS', 'Traditionele Marokkaanse pannenkoek met kaas.', 4.95, ARRAY['Gluten', 'Vegetarisch'], true, 22);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'MSEMEN / PANNENKOEK'), 'MSEMEN GRILLWORST', 'Traditionele Marokkaanse pannenkoek met grillworst.', 7.50, ARRAY['Gluten', 'Halal'], true, 23);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'MSEMEN / PANNENKOEK'), 'MSEMEN GEITENKAAS, WALNOOT EN HONING', 'Traditionele Marokkaanse pannenkoek met verse geitenkaas, Walnoot en Honing', 7.95, ARRAY['Gluten', 'Melk', 'Noten', 'Pinda''s', 'Vegetarisch'], true, 24);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'MSEMEN / PANNENKOEK'), 'MSEMEN NUTELLA', 'Traditionele Marokkaanse pannenkoek met Nutella.', 4.95, ARRAY['Gluten', 'Noten', 'Vegetarisch'], true, 25);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'MSEMEN / PANNENKOEK'), 'MSEMEN HAM - KAAS', 'Traditionele Marokkaanse pannenkoek met ham en kaas.', 5.95, ARRAY['Gluten', 'Halal'], true, 26);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'MSEMEN / PANNENKOEK'), 'MSEMEN LA VACHE QUI RIT EN HONING', null, 5.95, ARRAY['Gluten', 'Melk'], true, 27);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'PANINI''S'), 'GRILLWORST NATUREL', null, 5.95, ARRAY['Gluten', 'Halal'], true, 28);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'PANINI''S'), 'GRILLWORST KAAS', null, 5.95, ARRAY['Gluten', 'Halal'], true, 29);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'PANINI''S'), 'GRILLWORST PIKANT', null, 5.95, ARRAY['Pittig', 'Gluten', 'Halal'], true, 30);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'PANINI''S'), 'MOZZERALLA PESTO TOMAAT', null, 5.95, ARRAY['Gluten', 'Melk', 'Vegetarisch'], true, 31);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'PANINI''S'), 'PANINI TONIJN', null, 5.95, '{}', true, 32);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'PANINI''S'), 'PANINI KIP', null, 5.95, '{}', true, 33);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'PANINI''S'), 'PANINI HETE KIP', null, 5.95, '{}', true, 34);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'BELEGDE BROODJES'), 'GEZOND', 'Belegen kaas, ham, sla, komkommer, tomaat, ui', 6.50, ARRAY['Ei', 'Gluten', 'Halal'], true, 35);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'BELEGDE BROODJES'), 'KAAS', 'Belegen kaas', 3.95, ARRAY['Gluten'], true, 36);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'BELEGDE BROODJES'), 'HAM - KAAS', 'Belegen kaas en ham', 4.95, ARRAY['Gluten', 'Halal'], true, 37);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'BELEGDE BROODJES'), 'GRILLWORST', 'Grillworst en salade', 6.50, ARRAY['Gluten', 'Halal'], true, 38);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'BELEGDE BROODJES'), 'ZALM', 'Smeerkaas, zalm en salade.', 6.95, ARRAY['Gluten', 'Vis'], true, 39);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'BELEGDE BROODJES'), 'BROODJE EI-SPECIAAL', 'Roerei, chatarworst, geraspte kaas en La''vache qui rit', 7.95, ARRAY['Ei', 'Gluten', 'Halal'], true, 40);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'BELEGDE BROODJES'), 'BROODJE BENNY''S', 'Ei, Grillworst en Kaas', 7.95, ARRAY['Ei', 'Gluten', 'Halal'], true, 41);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'HARTIGE HAPJES'), 'HARCHA (GRIESMEEL)', null, 2.95, ARRAY['Gluten', 'Melk', 'Noten', 'Vegetarisch'], true, 42);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'HARTIGE HAPJES'), 'PATATJE', 'Met mayo en ketchup', 4.50, ARRAY['Ei', 'Gluten', 'Melk', 'Mosterd', 'Selderij'], true, 43);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'HARTIGE HAPJES'), 'Baghrir', null, 2.95, '{}', true, 44);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'HARTIGE HAPJES'), 'briwat kip', null, 3.50, '{}', false, 45);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'HARTIGE HAPJES'), 'Kip Loempia', null, 2.50, ARRAY['Ei', 'Gluten', 'Melk', 'Noten', 'Pinda''s', 'Sesam'], false, 46);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'WARME BROODJES'), 'BROODJE KIP SATÉ', null, 10.95, ARRAY['Gluten', 'Noten', 'Halal'], true, 47);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'WARME BROODJES'), 'BROODJE HETE KIP', null, 10.95, ARRAY['Pittig', 'Gluten', 'Halal'], true, 48);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'WARME BROODJES'), 'BROODJE MERGUEZ', null, 11.95, ARRAY['Mild', 'Gluten', 'Selderij', 'Halal'], true, 49);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'WARME BROODJES'), 'BROODJE GARNAAL', null, 11.95, ARRAY['Mild', 'Gluten', 'Schaal- en schelpdieren', 'Selderij', 'Vis'], true, 50);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'WARME BROODJES'), 'BROODJE KIP - GARNAAL', null, 12.95, ARRAY['Mild', 'Gluten', 'Schaal- en schelpdieren', 'Selderij', 'Vis', 'Halal'], true, 51);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'WARME BROODJES'), 'BROODJE KEFTA', null, 11.95, '{}', true, 52);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'WARME BROODJES'), 'Broodje Kip', null, 10.95, ARRAY['Gluten', 'Noten', 'Halal'], true, 53);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'SOEP'), 'BISSARA (erwtensoep)', 'Word geserveerd met brood. Eettip; voeg olijfolie en komijn toe.', 5.95, ARRAY['Vegetarisch', 'Veganistisch'], false, 54);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'SOEP'), 'HARIRA (traditionele Marokkaanse soep)', 'Word geserveerd met brood, citroen en dadel.', 5.95, ARRAY['Gluten', 'Selderij', 'Halal'], false, 55);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'SALADES'), 'GRILLED CAJUN CHICKEN SALADE', 'Bedje van verse sla melange, gemengd met komkommer, tomaat, avocado, ei en kip.', 9.95, ARRAY['Mild', 'Ei', 'Selderij', 'Halal'], true, 56);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'SALADES'), 'CEASER SALADE MET GAMBA', 'Bedje van verse sla melange, gemengd met komkommer, tomaat, avocado, ei en gamba.', 10.95, ARRAY['Mild', 'Ei', 'Schaal- en schelpdieren', 'Selderij', 'Vis'], true, 57);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'SALADES'), 'TUNA', 'Bedje van verse sla melange, gemengd met komkommer, tomaat, avocado, ei en tonijn', 7.95, '{}', true, 58);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'SMOOTHIES'), 'AARDBEI', null, 5.95, ARRAY['Vegetarisch'], true, 59);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'SMOOTHIES'), 'BANAAN', null, 5.95, ARRAY['Vegetarisch'], true, 60);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'SMOOTHIES'), 'BOSVRUCHTEN', null, 5.95, ARRAY['Noten', 'Vegetarisch'], true, 61);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'SMOOTHIES'), 'KIWI - MANGO', null, 5.95, ARRAY['Noten', 'Vegetarisch'], true, 62);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'SMOOTHIES'), 'MANGO - AARDBEI', null, 5.95, ARRAY['Vegetarisch'], true, 63);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'SMOOTHIES'), 'EIGENWIJSJE', null, 5.95, ARRAY['Vegetarisch'], true, 64);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'SMOOTHIES'), 'KIWI - BANAAN', 'Kiwi - Banaan', 5.95, ARRAY['Vegetarisch'], true, 65);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'SMOOTHIES'), 'MANGO', 'Mango', 5.95, '{}', true, 66);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'SMOOTHIES'), 'JUS D ORANGE', null, 3.95, '{}', true, 67);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'MILKSHAKES'), 'BANAAN', null, 5.95, ARRAY['Melk'], true, 68);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'MILKSHAKES'), 'AVOCADO SPECIAL', null, 6.95, ARRAY['Melk', 'Noten'], true, 69);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'MILKSHAKES'), 'AARDBEI - BANAAN', null, 5.95, ARRAY['Melk'], true, 70);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'MILKSHAKES'), 'BOSVRUCHTEN', null, 5.95, ARRAY['Melk', 'Noten'], true, 71);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'MILKSHAKES'), 'MANGO', null, 5.95, '{}', true, 72);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'MILKSHAKES'), 'AVOCADO', null, 5.95, '{}', true, 73);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'MILKSHAKES'), 'AARDBEI', null, 5.95, '{}', true, 74);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'WARME DRANKJES'), 'MAROKKAANSE THEE', null, 2.95, '{}', true, 75);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'WARME DRANKJES'), 'THEE', null, 2.95, ARRAY['Vegetarisch'], true, 76);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'WARME DRANKJES'), 'GEMBER THEE', null, 3.95, ARRAY['Vegetarisch'], true, 77);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'WARME DRANKJES'), 'MUNT THEE', null, 2.95, ARRAY['Vegetarisch'], true, 78);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'WARME DRANKJES'), 'KOFFIE', null, 2.95, ARRAY['Vegetarisch'], true, 79);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'WARME DRANKJES'), 'ESPRESSO', null, 2.95, ARRAY['Vegetarisch'], true, 80);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'WARME DRANKJES'), 'DUBBELE ESPRESSO', null, 3.95, ARRAY['Vegetarisch'], true, 81);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'WARME DRANKJES'), 'CAPPUCCINO', null, 3.95, ARRAY['Melk'], true, 82);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'WARME DRANKJES'), 'CAPPUCCINO GROOT', null, 4.50, ARRAY['Melk'], true, 83);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'WARME DRANKJES'), 'NAS/NAS', 'marokaanse koffie', 3.95, '{}', true, 84);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'WARME DRANKJES'), 'LATTE MACCHIATO', null, 4.50, ARRAY['Melk'], true, 85);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'WARME DRANKJES'), 'CORTADO', null, 3.50, ARRAY['Melk'], true, 86);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'WARME DRANKJES'), 'KOFFIE VERKEERD', null, 3.95, '{}', true, 87);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'WARME DRANKJES'), 'WARME CHOCOMEL', null, 3.50, ARRAY['Melk', 'Noten'], true, 88);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'FRISDRANK'), 'Coca-Cola original taste 330ml', 'Coca-Cola Original Taste, een heerlijke en verfrissende bruisende frisdrank, voor het eerst ontwikkeld in 1886, met een geweldige smaak. Made for sharing', 2.95, '{}', true, 89);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'FRISDRANK'), 'Coca-Cola zero sugar 330ml', 'Coca-Cola Zero heeft dezelfde legendarische Coca-Cola smaak, maar dan zonder suiker. Een verfrissend zachte en lekkere bruisende frisdrank, perfect om te delen', 2.95, '{}', true, 90);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'FRISDRANK'), 'Fanta orange 330ml', 'Fanta Orange: de iconische, heerlijke bruisende frisdrank gemaakt met vruchtensap. Perfect voor snacken en ontwikkeld om kleur aan je leven toe te voegen', 2.95, '{}', true, 91);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'FRISDRANK'), 'Sprite zero sugar 330ml', 'Laat je ware ik sprankelen met Sprite: een zuivere, fris smakende, bruisende limoen- en citroenfrisdrank. 100% natuurlijke aroma''s, zonder suiker, zonder calorieën.', 2.95, '{}', true, 92);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'FRISDRANK'), 'AA', null, 2.95, '{}', true, 93);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'FRISDRANK'), 'SPA BLAUW', null, 2.50, '{}', true, 94);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'FRISDRANK'), 'SPA ROOD', null, 2.50, '{}', true, 95);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'FRISDRANK'), 'CAPRI SUN', null, 1.50, '{}', true, 96);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'FRISDRANK'), 'ICE TEA GREEN', null, 2.95, '{}', true, 97);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'FRISDRANK'), 'CREAM SODA', null, 2.95, '{}', true, 98);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'FRISDRANK'), 'HAWAÏ', null, 2.95, '{}', true, 99);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'FRISDRANK'), 'APPELSAP', null, 2.95, '{}', true, 100);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'FRISDRANK'), 'FRISTI', null, 2.95, '{}', true, 101);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'FRISDRANK'), 'CHOCOMEL', null, 2.95, '{}', true, 102);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'FRISDRANK'), 'LIPTON PEACH', null, 2.95, '{}', true, 103);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'FRISDRANK'), 'Fernandes green punch 330ml', 'Fernandes green punch is een tropische frisdrank met een zoete vruchtensmaak. Het product komt oorspronkelijk uit Suriname.', 2.95, '{}', true, 104);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'FRISDRANK'), 'Fernandez blauwe', null, 2.95, '{}', true, 105);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'FRISDRANK'), 'Fernandez rood', null, 2.95, '{}', true, 106);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'FRISDRANK'), 'Fernandez geel', null, 2.95, '{}', true, 107);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'FRISDRANK'), 'Red bull', null, 3.35, '{}', true, 108);
insert into products (category_id, name, description, price, allergens, is_available, sort_order) values ((select id from categories where name = 'FRISDRANK'), 'Sprite', null, 2.95, '{}', true, 109);

-- De 15 tafels
insert into tables (table_number) values (1);
insert into tables (table_number) values (2);
insert into tables (table_number) values (3);
insert into tables (table_number) values (4);
insert into tables (table_number) values (5);
insert into tables (table_number) values (6);
insert into tables (table_number) values (7);
insert into tables (table_number) values (8);
insert into tables (table_number) values (9);
insert into tables (table_number) values (10);
insert into tables (table_number) values (11);
insert into tables (table_number) values (12);
insert into tables (table_number) values (13);
insert into tables (table_number) values (14);
insert into tables (table_number) values (15);
